// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5GJcsq2zryErjJ9dlsYaRxM_zaiwWylA',
    appId: '1:842766684888:web:027daed614ee7cbae53dad',
    messagingSenderId: '842766684888',
    projectId: 'labor-link-f9424',
    authDomain: 'labor-link-f9424.firebaseapp.com',
    storageBucket: 'labor-link-f9424.appspot.com',
    measurementId: 'G-N0WNQXWYF9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBy7lgp3RSE-ykeHTpwnEBpe-uW9deV90E',
    appId: '1:842766684888:android:011dd0cc8b4a663ae53dad',
    messagingSenderId: '842766684888',
    projectId: 'labor-link-f9424',
    storageBucket: 'labor-link-f9424.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7kBwBeIdTAgVrM6lyNmBfZptarOUPfOU',
    appId: '1:842766684888:ios:4b8804ea9e8e9dfbe53dad',
    messagingSenderId: '842766684888',
    projectId: 'labor-link-f9424',
    storageBucket: 'labor-link-f9424.appspot.com',
    iosBundleId: 'com.example.laborLinkMobile',
  );
}
